/* Generated by Yosys 0.10+1 (git sha1 UNKNOWN, gcc 11.2.1 -O2 -fexceptions -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -Os) */

(* dynports =  1  *)
(* src = "adder.sv:1.1-19.10" *)
module adder(i_a, i_b, o_sum, o_carry);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  (* src = "adder.sv:4.35-4.38" *)
  input [3:0] i_a;
  (* src = "adder.sv:4.40-4.43" *)
  input [3:0] i_b;
  (* src = "adder.sv:6.25-6.32" *)
  output o_carry;
  (* src = "adder.sv:5.35-5.40" *)
  output [3:0] o_sum;
  assign _00_ = i_a[3] ^ i_b[3];
  assign _01_ = ~_00_;
  assign _02_ = ~(i_a[2] & i_b[2]);
  assign _03_ = i_a[2] ^ i_b[2];
  assign _04_ = ~(i_a[1] & i_b[1]);
  assign _05_ = i_a[1] ^ i_b[1];
  assign _06_ = ~(i_a[0] & i_b[0]);
  assign _07_ = _05_ & ~(_06_);
  assign _08_ = _04_ & ~(_07_);
  assign _09_ = _03_ & ~(_08_);
  assign _10_ = _02_ & ~(_09_);
  assign o_sum[3] = _10_ ^ _01_;
  assign _11_ = ~(o_sum[3] ^ i_a[3]);
  assign o_carry = _01_ & ~(_11_);
  assign o_sum[1] = ~(_06_ ^ _05_);
  assign o_sum[2] = ~(_08_ ^ _03_);
  assign o_sum[0] = i_a[0] ^ i_b[0];
endmodule
