/* Generated by Yosys 0.10+1 (git sha1 UNKNOWN, gcc 11.2.1 -O2 -fexceptions -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -Os) */

module gray_koder2(i_data, o_gray);
  wire _0_;
  wire _1_;
  input [3:0] i_data;
  output [3:0] o_gray;
  assign _1_ = i_data[1] ^ i_data[0];
  assign o_gray[0] = _1_ | i_data[3];
  assign _0_ = i_data[2] ^ i_data[1];
  assign o_gray[1] = _0_ | i_data[3];
  assign o_gray[2] = i_data[2] | i_data[3];
  assign o_gray[3] = i_data[3];
endmodule
