/* Generated by Yosys 0.10+1 (git sha1 UNKNOWN, gcc 11.2.1 -O2 -fexceptions -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -Os) */

module onehot2nkb_encoder(i_onehot, o_nkb);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  input [3:0] i_onehot;
  output [1:0] o_nkb;
  assign _06_ = ~i_onehot[2];
  assign _07_ = i_onehot[0] | i_onehot[1];
  assign _08_ = _06_ & ~(_07_);
  assign _00_ = _08_ & ~(i_onehot[3]);
  assign _01_ = i_onehot[2] ? _07_ : i_onehot[1];
  assign _02_ = _01_ | i_onehot[3];
  assign o_nkb[0] = _02_ | _00_;
  assign _03_ = i_onehot[0] & i_onehot[1];
  assign _04_ = _03_ | i_onehot[2];
  assign _05_ = _04_ | i_onehot[3];
  assign o_nkb[1] = _05_ | _00_;
endmodule
