/* Generated by Yosys 0.10+1 (git sha1 UNKNOWN, gcc 11.2.1 -O2 -fexceptions -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -Os) */

module sm_to_u2(i_a, o_u2code);
  wire _0_;
  wire _1_;
  wire _2_;
  input [3:0] i_a;
  output [3:0] o_u2code;
  assign _2_ = i_a[0] ^ i_a[1];
  assign o_u2code[1] = i_a[3] ? _2_ : i_a[1];
  assign _0_ = i_a[0] | i_a[1];
  assign _1_ = _0_ ^ i_a[2];
  assign o_u2code[2] = i_a[3] ? _1_ : i_a[2];
  assign { o_u2code[3], o_u2code[0] } = { i_a[3], i_a[0] };
endmodule
